package com.chatflow.consumerv3;

/**
 * One row in the canonical DynamoDB table {@code messages_by_id}.
 *
 * <pre>
 * PK : messageId  (S) — globally unique UUID, generated by server-v2
 * (no SK — single-attribute lookup only)
 * </pre>
 *
 * Fields {@code serverId}, {@code clientIp}, {@code dayBucket}, {@code eventTs}
 * are populated by {@link CanonicalMessageMapper} from the Protobuf payload.
 * {@code ingestedAt} is always set by the consumer side, never copied from
 * the client timestamp.
 */
public class CanonicalMessageRecord {

    // ── Primary key ───────────────────────────────────────────────────────────
    private String messageId;

    // ── Core message fields ───────────────────────────────────────────────────
    private String roomId;
    private String userId;
    private String username;
    private String message;
    private String messageType;    // TEXT / JOIN / LEAVE
    private long   roomSequence;

    // ── Timestamps ────────────────────────────────────────────────────────────
    /** Client-originated epoch-ms (parsed from proto {@code timestamp} string). */
    private long   eventTs;
    /**
     * Wall-clock epoch-ms when consumer-v3 confirmed the DynamoDB write.
     * Always set by the consumer, never copied from the client clock.
     */
    private long   ingestedAt;

    // ── Provenance ────────────────────────────────────────────────────────────
    /** server-v2 instance that published this message to RabbitMQ. */
    private String serverId;
    /** Client IP as seen by server-v2. */
    private String clientIp;

    // ── Partitioning helper ───────────────────────────────────────────────────
    /**
     * UTC date bucket "YYYY-MM-DD" derived from {@link #eventTs}.
     * Useful for time-range queries and TTL-based cleanup.
     */
    private String dayBucket;

    // ── Pipeline-internal (not written to DynamoDB) ───────────────────────────
    /**
     * AMQP delivery tag, kept here so the ack step can correlate write results
     * back to the original delivery without a separate map.
     * This field is intentionally excluded from {@link #toString()} and
     * must NOT be mapped to any DynamoDB attribute.
     */
    private transient long deliveryTag;

    // ── Constructors ──────────────────────────────────────────────────────────

    public CanonicalMessageRecord() {}

    public CanonicalMessageRecord(
            String messageId, String roomId, String userId, String username,
            String message, String messageType, long roomSequence,
            long eventTs, long ingestedAt,
            String serverId, String clientIp, String dayBucket,
            long deliveryTag) {
        this.messageId    = messageId;
        this.roomId       = roomId;
        this.userId       = userId;
        this.username     = username;
        this.message      = message;
        this.messageType  = messageType;
        this.roomSequence = roomSequence;
        this.eventTs      = eventTs;
        this.ingestedAt   = ingestedAt;
        this.serverId     = serverId;
        this.clientIp     = clientIp;
        this.dayBucket    = dayBucket;
        this.deliveryTag  = deliveryTag;
    }

    // ── Getters / Setters ─────────────────────────────────────────────────────

    public String getMessageId()       { return messageId; }
    public void   setMessageId(String v) { this.messageId = v; }

    public String getRoomId()          { return roomId; }
    public void   setRoomId(String v)  { this.roomId = v; }

    public String getUserId()          { return userId; }
    public void   setUserId(String v)  { this.userId = v; }

    public String getUsername()        { return username; }
    public void   setUsername(String v){ this.username = v; }

    public String getMessage()         { return message; }
    public void   setMessage(String v) { this.message = v; }

    public String getMessageType()     { return messageType; }
    public void   setMessageType(String v) { this.messageType = v; }

    public long   getRoomSequence()    { return roomSequence; }
    public void   setRoomSequence(long v) { this.roomSequence = v; }

    public long   getEventTs()         { return eventTs; }
    public void   setEventTs(long v)   { this.eventTs = v; }

    public long   getIngestedAt()      { return ingestedAt; }
    public void   setIngestedAt(long v){ this.ingestedAt = v; }

    public String getServerId()        { return serverId; }
    public void   setServerId(String v){ this.serverId = v; }

    public String getClientIp()        { return clientIp; }
    public void   setClientIp(String v){ this.clientIp = v; }

    public String getDayBucket()       { return dayBucket; }
    public void   setDayBucket(String v){ this.dayBucket = v; }

    public long   getDeliveryTag()     { return deliveryTag; }
    public void   setDeliveryTag(long v){ this.deliveryTag = v; }

    @Override
    public String toString() {
        return "CanonicalMessageRecord{messageId='" + messageId
            + "', roomId='" + roomId + "', userId='" + userId
            + "', seq=" + roomSequence + ", dayBucket='" + dayBucket + "'}";
    }
}
