jvmOpts: "-Xms1g -Xmx2g"
client:
  serverUrl: "ws://chatflow-a2-alb-1277626986.us-west-2.elb.amazonaws.com/chat"
  totalMessages: 500000
  warmupThreads: 32
  warmupMessagesPerThread: 1000
  mainThreads: 64
  targetQps: 2500
  connectionsPerRoom: 1
  handshakeTimeoutSeconds: 20
  maxConcurrentHandshakes: 32
  handshakeRetryDelayMs: 10
  responseWaitSeconds: 600
  batchSize: 40
  batchMaxBytes: 32768
  flushIntervalMs: 1
  flushSync: false
